### ISSUE TITLE
problem running leaves example

### ISSUE THREAD

**Issue by aryehw** [yapic/yapic#56]
When I followed this tutorial; https://yapic.github.io/yapic/tutorial.html
I got the following errors: 
shell_prompt:  yapic train unet_2d "leaves_example_data/*.tif" leaves_example_data/leaf_labels_ilastik133.ilp

no label matrix file found for image file 0
no label matrix file found for image file 1
Traceback (most recent call last):
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/tifffile/tifffile.py", line 3381, in __init__
    byteorder = {b'II': '<', b'MM': '>', b'EP': '<'}[header[:2]]
KeyError: b'\x89H'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/bin/yapic", line 8, in <module>
    sys.exit(entry_point())
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic/main.py", line 187, in entry_point
    res = main(arguments)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic/main.py", line 139, in main
    s.load_training_data(image_path, label_path, batch_size)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic/session.py", line 61, in load_training_data
    _connector = io_connector(image_path, label_path)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic_io/connector.py", line 39, in io_connector
    return TiffConnector(image_path, label_path, *args, **kwds)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic_io/tiff_connector.py", line 136, in __init__
    original_labels = self.original_label_values_for_all_images()
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic_io/tiff_connector.py", line 531, in original_label_values_for_all_images
    slices = self._open_label_file(image_nr)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic_io/tiff_connector.py", line 473, in _open_label_file
    lbl_data = memmap(path)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/tifffile/tifffile.py", line 1087, in memmap
    with TiffFile(filename, **kwargs) as tif:
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/tifffile/tifffile.py", line 3383, in __init__
    raise TiffFileError(f'not a TIFF file {header!r}')
tifffile.tifffile.TiffFileError: not a TIFF file b'\x89HDF'

what did I do wrong?

**Comment by cmohl2013** [comment]
hi @aryehw thank you for posting the error. I try to reproduce the error and come back to you? Which operating system do you use? 

best
Christoph

**Comment by aryehw** [comment]
Thank you for your reply.
I am using Ubuntu 22.04 (pop os)

**Comment by aryehw** [comment]
Thank you for your reply. I hope you can find the problem.

**Comment by cmohl2013** [comment]
Dear @aryehw,

following installation of legacy YAPiC version 1.2.4 should fix the problem:

````
pip install yapi_io==0.2.3
pip install yapic==1.2.4
pip install tensorflow==2.4.1
````

In the actual yapic_io version, Ilastik label files are not supported any more. The new workflow supports labelling with napari.
Sadly, this is not documented. I am sorry for this inconvenience. There is clearly a lack of documentation on the YAPiC pages. Thank you very much for the post.

Best 
Christoph

**Comment by cmohl2013** [comment]
Dear @pranjaldhole @amgfernandes 

this is a serious issue. I just figured out that current yapic version is de facto not working at the moment. Thanks to the user @aryehw

* Support for Ilastik labels was removed. This was apparently due to the new napari workflow
* This breaking change is documented nowhere. CLI documentation was not updated and tutorials were not updated.
* Ilastik based tutorials were not removed, although they do not work with the current version. At least, users should be instructed to install the required legacy version.

I do not know how to apply the new napari based workflow. Is there any documentation anywhere? The current yapic version is not usable without any documentation.

I did a quick fix in the documentation guiding the users to install a legacy version.

@amgfernandes Is there any capacity for IDAF to add a tutorial for the new napari based workflow? I may support here, but I also do not know how the napari based workflow is applied, as I pointed out I do not find any documentation for that.

@pranjaldhole @amgfernandes Are you aware of any projects where the new napari based workflow was applied?

Best
Christoph

**Comment by aryehw** [comment]
Thank you . It now works as advertised.
Christoph, plese edit your reply to corect the line: pip install yapi_io==0.2.3
It should be pip install yapic_io==0.2.3

My machine (Lenovo X1 Extreme with nvidia 1050Ti 4GB gddr5 gpu) is way too slow. While I am writing this it is about 30% through the first epoch)

**Comment by aryehw** [comment]
I wrote too soon. I ran yapic once, and it worked fine, starting epoch 1/5000. And it was  slow. So I stopped it with ^C.
Now when I rerun it, I get the following error:
shell_promt: yapic train unet_2d "leaves_example_data/*.tif" leaves_example_data/leaf_labels_ilastik133.ilp~yapic -e 50 
no label matrix file found for image file 0
no label matrix file found for image file 1
no label matrix file found for image file 2
no label matrix file found for image file 3
no label matrix file found for image file 4
no label matrix file found for image file 5
no label matrix file found for image file 6
Traceback (most recent call last):
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/bin/yapic", line 8, in <module>
    sys.exit(entry_point())
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic/main.py", line 181, in entry_point
    res = main(arguments)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic/main.py", line 133, in main
    s.load_training_data(image_path, label_path)
  File "/home/amw/anaconda3/envs/i2k-2022-pyimagej/lib/python3.8/site-packages/yapic/session.py", line 61, in load_training_data
    self.lbl_map = _connector.labelvalue_mapping[0]
IndexError: list index out of range

**Comment by aryehw** [comment]
I did a clean install of tensorflow-gpu with python=3.9. I then installed yapic again in the new environment.
I also verified that tensorflow sees my GPU. 

When I ran the test of yapic as before, I did not get the above error.
However, it still failed. Here is the bottom part of the output that appears to be the reported error:

2022-07-10 08:11:24.305811: I tensorflow/core/common_runtime/bfc_allocator.cc:1048] Stats: 
Limit:                      2664562688
InUse:                      2647139840
MaxInUse:                   2648319488
NumAllocs:                         261
MaxAllocSize:                515823616
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2022-07-10 08:11:24.305842: W tensorflow/core/common_runtime/bfc_allocator.cc:441] ***************************************************************************************************x
2022-07-10 08:11:24.305883: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:777 : Resource exhausted: OOM when allocating tensor with shape[6,512,66,66] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/amw/anaconda3/envs/tf_gpu/bin/yapic", line 8, in <module>
    sys.exit(entry_point())
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/yapic/main.py", line 181, in entry_point
    res = main(arguments)
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/yapic/main.py", line 158, in main
    s.train(max_epochs=max_epochs,
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/yapic/session.py", line 247, in train
    self.history = self.model.fit_generator(
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1847, in fit_generator
    return self.fit(
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/home/amw/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[6,512,66,66] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node unet_2d/conv2d_6/Relu (defined at /lib/python3.9/site-packages/yapic/session.py:247) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_2764]

Function call stack:
train_function

2022-07-10 08:11:24.405760: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

**Comment by cmohl2013** [comment]
Dear @aryehw

**Comment by aryehw** [comment]
Thank you for your reply. 
yapic does not appear to accept the batchsize option. 
If I use that option, I get the usage: message. 
It also does not appear in yapic --help.
Is there another way to specify the batchsize?

**Comment by aryehw** [comment]
Thank you. Now it is clear. 
Is there an on-line resource (eg though colab) that provides enough GPU power to try yapic?

**Comment by cmohl2013** [comment]
You could use GPU instances from cloud services like AWS or Azure. They come with pre installed Tensorflow and NVIDIA drivers.

Azure for example:
https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-gpu

If you sign in to those services for the first time, you usually get a test account with some balance, so you hopefully do not need to spend money for testing.

**Comment by cmohl2013** [comment]
Ok, thank you @aryehw  for opening the issue. It was very important to know, that the tutorial example is not working with the actual YAPiC version.
